ALTER TABLE vouchers ADD COLUMN IF NOT EXISTS project_id UUID REFERENCES projects(id) ON DELETE SET NULL;

ALTER TABLE liquidations ADD COLUMN IF NOT EXISTS personnel_id UUID REFERENCES personnel(id) ON DELETE SET NULL;
ALTER TABLE liquidations ADD COLUMN IF NOT EXISTS project_id UUID REFERENCES projects(id) ON DELETE SET NULL;
ALTER TABLE liquidations ADD COLUMN IF NOT EXISTS receipt_attached BOOLEAN DEFAULT false;